### ISSUE TITLE
How to build from source code?

### ISSUE THREAD

**Issue by ssainz** [cckuailong/YarnRpcRCE#1]
Hello - wanted to build from source code and tried 

```
mvn package
```

And I get at the end a war file, but later from war file cannot executed the YarnRpc with command like 

```
java -cp C:\hadoop_yarn\YarnRpcRCE\target\YarnRpcUnauth.war YarnRpc 127.0.0.1:8032  "touch /tmp/success"
Error: Could not find or load main class YarnRpc
Caused by: java.lang.ClassNotFoundException: YarnRpc
```

from a look inside of the `YarnRpcUnauth.jar ` there seems to be a fat-jar that incorporates the war plus fat-jar. Is there some missing script for this?

**Comment by cckuailong** [comment]
I have included all the lib int the jar, so it looks fat. I build it with IDEA.
